# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GRAILS_HOME:  /home/runner/work/githubactiontest/githubactiontest/grails-2.5.6

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - run: pwd
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 8.0.302-open
      - uses: actions/setup-java@v1
        id: setup-java
        with:
          java-version: 8.0.302
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - run: java -version
      - run: curl -o grails.zip http://143.198.12.177/grails-2.5.6.zip
      - run: unzip grails.zip
      - run: echo $GRAILS_HOME
      - run: $GRAILS_HOME/bin/grails set-grails-version 2.5.6
      - run: $GRAILS_HOME/bin/grails -version
      - run: $GRAILS_HOME/bin/grails run-app
